name: Swift

on:
  schedule:
    - cron:  '0 7 * * *'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
         github_token: ${{ secrets.WALLPAPER_ACTION_TOKEN }}
         branch: main
    - name: Run
      run: swift run
      
    - name: Commit files
      run: |
         git config --global user.email "jie_liu3@icloud.com"
         git config --global user.name "Zijie Liu"
         git add .
         git commit -m "Update json"
         git pull --rebase origin main
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
         github_token: ${{ secrets.WALLPAPER_ACTION_TOKEN }}
         branch: main
